# Imagem base com Python 3.12
FROM python:3.12-slim

# Diretório de trabalho no contêiner
WORKDIR /app

# Copia os arquivos do diretório local para o diretório de trabalho no contêiner
COPY . .

# Instala as dependências
RUN pip install flask requests

# Expor a porta 9999 para o servidor Flask
EXPOSE 9999

# Comando para iniciar o servidor Flask quando o contêiner for executado
CMD ["python", "app.py"]
