# Imagem base com Python 3.12
FROM python:3.12-slim

# Diretório de trabalho no contêiner
WORKDIR /app

# Copiar o restante do código da aplicação para o diretório de trabalho
COPY tabela_roteamento.py .

# Instalar as dependências
RUN pip install --no-cache-dir flask

# Expor a porta em que a tabela de roteamento vai rodar
EXPOSE 4326

# Comando para rodar a aplicação Flask
CMD ["python", "tabela_roteamento.py"]
